@startuml Titre
'--------------------------------
' Parametres pour le dessin
'--------------------------------
hide circle
hide empty members
hide empty methods
'--------------------------------
class Point{
}

class Ligne{
}

Ligne "0..*" -- "2" Point

@enduml