@startuml Ordinateurs portables
'--------------------------------
' Parametres pour le dessin
'--------------------------------
hide circle
hide empty members
hide empty methods
'--------------------------------

class "Ordinateur"{
clavier
valeur actuelle
}

class Clavier{
    azerty ou qwerty
    touches
}

class Proprietaire{
    Nom
    Prénom
}

Ordinateur "1" - "1" Clavier
Ordinateur "1 " --- "1 " Proprietaire

(Ordinateur, Clavier) . Posséder
(Ordinateur, Proprietaire) . Acheter

class Acheter {
    prix d'achat
}

@enduml
